### ISSUE TITLE
Fix account_holder edge creation out of the data preparation service

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#110]
Is bug. Make fix.

**Comment by Justus-Ortlepp-frms** [comment]
Something is broken here. I am trying to send in a pain.001 transaction via the TMS API. I can see the transaction passing through APM:

![Image](https://github.com/frmscoe/General-Issues/assets/123470803/5f4283d5-03a1-4b94-9bc1-a66e555f100c)

I can see the transaction in the pain.001 message history here:

![Image](https://github.com/frmscoe/General-Issues/assets/123470803/21427542-da4d-4577-ae25-6d1cfcb50943)

Even though APM reports that the steps to build the graph have been completed, there is nothing in the graph for this EndToEndId:


![Image](https://github.com/frmscoe/General-Issues/assets/123470803/08dd85d9-95d1-454a-beab-251aa7b6d43d)


![Image](https://github.com/frmscoe/General-Issues/assets/123470803/4dc7b51c-5c47-4da6-a432-9a88df30d647)

Help me, @JeanPierreNell , you're my only hope...
