### ISSUE TITLE
Create a generic "fetch account ID" function in the library

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#111]
Create a `fetchAccountIdentifiers` library function that takes in the trigger payload...

<snip> and a switch parameter for the `accountType` to return (0 for both, etc). First attempt to look up the identifiers in the trigger payload's `DataCache` object. If the one(s) we are looking for, based on the `accountType` switch, are not in the `DataCache`, use the `EndToEndId` from the trigger payload and the `TxTp` from the trigger payload to look up the account identifiers in the same `TxTp` in the `transactionRelationship` collection.

```javascript
FOR pacs008 IN transactionRelationship
    FILTER pacs008.EndToEndId == ${endToEndId}
    AND pacs008.TxTp == "pacs.008.001.10"
RETURN { "debtorAccountId": pacs008._from, "creditorAccountId": pacs008._to }
```
</snip>

Edit: We decided to populate the entire complete DataCache object out of #76 so that every message will always have all of the available fields:

```json
DataCache: {
  "dbtrId": "debtor identifier",
  "dbtrAcctId": "debtor account identifier",
  "cdtrId": "creditor identifier",
  "cdtrAcctId": "creditor account identifier"
}
```

The library function to collect this information must return the entire DataCache object from the payload, and if it doesn't exist, try to retrieve the whole object from Redis cache, and if it doesn't exist, try to build the entire object out of the graph in Arango. In theory, we could use a graph traversal to collect all the nodes related to the EndToEndId in a single query, but Arango will not be able to start a traversal from an edge and will need either the debtor account identifier or the creditor account identifier to start the traversal, which means at least one read to the database just to fetch either one of those two things based on the pacs.002 EndToEndId. I'd like to avoid to many separate queries, if possible, but the best I can come up with at the moment is to fetch the account identifiers (dbtrAcctId and cdtrAcctId) from the transactionRelationship edge collection via the EndToEndId and then to fetch the entity identifiers (dbtrId and cdtrId) from the account_holder edge collection based on the dbtrAcctId and cdtrAcctId values previously retrieved. This feels clunky, but can probably be performed via subqueries to reduce the traffic to a single Arango call.

Also, remember to remove the `entities/` and `accounts/` prefixes from the results to align with the data that is originally expected out of the data preparation service.

```aql
LET accounts = (

FOR accts IN transactionRelationship
    FILTER accts.EndToEndId == "180fc2c4c1bb4b97b4db8f7e99c287fc"
    AND accts.TxTp == "pacs.002.001.12"
RETURN {"dbtrAcctId": accts._to, "cdtrAcctId": accts._from}
)

LET dbtrId = (
    FOR entities IN account_holder
        FILTER entities._to == accounts[0].dbtrAcctId
    RETURN entities._from
)

LET cdtrId = (
    FOR entities IN account_holder
        FILTER entities._to == accounts[0].cdtrAcctId
    RETURN entities._from
)

RETURN {"dbtrId": dbtrId[0], "cdtrId": cdtrId[0], "dbtrAcctId": accounts[0].dbtrAcctId, "cdtrAcctId": accounts[0].cdtrAcctId} 
```

This query works and returns:

```json
[
  {
    "dbtrId": "entities/dbtr_d0bf00216a2c4e189d8b134913f63fd0",
    "cdtrId": "entities/cdtr_560f163a5f24442caa660a29a948163e",
    "dbtrAcctId": "accounts/dbtrAcct_ed455a9a1a784dc89af957a629561db9",
    "cdtrAcctId": "accounts/cdtrAcct_ebbe6c94649e46ac9997311a74ba0539"
  }
]
```

but could probably be improved.

**Comment by johanfol** [comment]
DataCache is given to the Rule from the Rule Executer - so done.
