### ISSUE TITLE
Create an Apache 2.0 SPDX header in all files

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#115]
As a platform operator,
I want an open source license header in every file in the open source repository,
So that I can be assured that I am using, and an able to use, the software under appropriate licensing conditions.

## Acceptance criteria

1. Add the following string as a comment at the top of every file in the FRMS organisation in GitHub that is capable of including a comment (i.e. no JSON files):

> SPDX-License-Identifier: Apache-2.0

Add the Apache 2.0 file to the root of all repositories: `LICENSE`

**Comment by Justus-Ortlepp-frms** [comment]
Side-quest:

Check if there's a way to automate this across the project
Check if we can add a check for this text in the pre-commit script

**Comment by Justus-Ortlepp-frms** [comment]
@cshezi - please confirm if the LICENSE file has been added to all repositories

**Comment by cshezi** [comment]
TMS is waiting for https://github.com/frmscoe/tms-service/pull/151 to be merged to resolve the ReadMe file name conflict
