### ISSUE TITLE
Implement NATS across the platform

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#133]
Implement NATS end-to-end across the platform between all the processors as follows:

![image](https://github.com/frmscoe/General-Issues/assets/123470803/de15d7cd-bc09-414b-8f07-d19ee8e60ccd)

![image](https://github.com/frmscoe/General-Issues/assets/123470803/8590b708-692a-4c15-ac13-98a270ffb669)

### 1-to-1 message distribution

For 1-to-1 (point-to-point) processor interaction, the pub-sub is straightforward. For example, the TMS API to the Data Preparation Service only needs a single output `subject` for the TMS to publish to and it is that same `subject` that the Data Preparation Service subscribes to.

### 1-to-many message distribution

For 1-to-many interaction, the pub-sub is also straightforward, but two options are available. You can either publish the solo processor's output only once to a single `subject` that is then linked to the publisher and where the multiple subscribers can subscribe to and fetch their input. The alternative is for the solo processor to publish the result to each of the downstream processors' individual `subjects`, once per downstream processor. For example, the CRSP needs to "fan out" to multiple rule processors. You can either publish to a single CRSP output `subject` and get each rule processor to subscribe, or you can publish to each individual rule processor's input `subject`. The impact of the decision:

#### Publish to one `subject` with multiple subscribers:

This approach seems to be something of a NATS default: https://docs.nats.io/nats-concepts/core-nats/pubsub

Simultaneously, this approach departs from Actio's current architecture. Actio is a forward-chaining event-driven platform. Downstream processors don't know when they will be required by upstream processors; upstream processors direct the flow of traffic to the specific downstream processors that are needed.

If we change the approach so that downstream processors (rules) need to know to which events out of the CRSP they are supposed to subscribe to when there is a single `subject` coming out of the CRSP, the rules will pretty much have to evaluate every message and then decide if it is for their attention.

One way to work around this would be to create specific typology `subjects` and then set up a group of rules to listen to that `subject` so that when the CRSP determines that a specific typology is necessary for an event, it can then publish the message to that typology `subject`. Rules would then have to subscribe to multiple typology `subjects`. This approach seems to require some kind of orchestrator to determine when all the required rules had collected their results, and again, the rules will need to already know which typology `subjects` to subscribe to. It gets a bit weird when a rule is subscribed to multiple typologies since it should only process a specific message from the first typology it gets it from. 

This approach makes run-time configurability very difficult (impossible without architectural changes) and the routing will effectively be deployment-specific. In other words, once a typology and its cluster of rules are set up at deployment-time, you would need to redeploy the rules to change the composition of the typology, or you would need some kind of external controlling process to trigger an update of a typology's subscribers in run-time.

I am also not entirely sure how NATS determines that all the required rules had collected the results they had subscribed to, though since this is the default behaviour, I assume the mechanism either exists or doesn't matter.

#### Publish to multiple `subjects` with single subscribers:

This approach is similar to the platform's current architecture. The CRSP still determines which rules are required for an evaluation and then sends the trigger payload to all the rule processors individually through their "personal" incoming subjects.

While adding resilience in the event of rule processor failure, this approach is largely similar to just sending the message directly to the rule processor and does not especially leverage pub-sub functionality.

#### Recommendation

Implement the 1-to-many distribution in a multiple subjects to single subscribers pattern (for now).

### Many-to-1 message distribution

Many-to-1 message distribution ("fanning in") is the most complicated of the three requirements, and also the most important. This is where multiple processor outcomes are aggregated by another processor and occurs in the typology processor (aggregating rule results), the CADProc (aggregating typology results) and the TADProc (aggregating channel results).

**Note:** *To be more accurate though, the typology processor is effectively a many-to-many aggregation, but in the current design, the typology processor is a single processor, so we'll leave the many-to-many question unanswered for now.*

The only way to implement the many-to-1 pattern is to let all of the upstream processors publish their results to their own downstream `subject` to which the downstream processor subscribes.

The *only* way? Well, kinda yes, maybe. In the 1-to-many pattern where we are publishing to a single `subject` for all the rules, the challenge was that the rules would be expected to know which messages to the `subject` they should ignore. The typology processor has the same problem. Not every typology needs every rule result, but the single typology processor won't be able to know which rule results to pick up for a specific typology, so it will have to pick up all the rule results all the time. The typology processor will have to subscribe to all the rule `subjects`.

For each rule to publish their results on their own `subject` makes sense from a scaling perspective though, since we are spreading out the load and we allow the typology processor to come and collect its inputs in its own time. If we were to aggregate all rule results into the same `subject`, the `subject` could become overwhelmed and will itself need to scale up to the level of the typology processor; now it just needs to scale up to the level of the rule processor.

For the remaining processors, even though the traffic itself "fans in", the processors are single processors: one CADProc, one TADProc, one CMS. We only need a single subject between them, similar to the 1-to-1 pattern above.

### Many-to-many message distribution

In reality the Typology processor and the CADProc are effectively many-to-many message handlers; we've just collapsed their functioning into a single processor that iterates over the incoming results. We may have to change this approach to be able to scale more accurately. Rule processors submit their results to multiple different typologies, in a chaotic flow-pattern. It may make sense for us to create a specific typology processor for each typology that then only subscribes to the `subjects` for the rules that make up the typology, but we will again be faced with a lost of run-time flexibility that we will have to manage. The CADProc has the same issue, albeit on a smaller scale. We'll address this problem in a future iteration of the architecture.

In the meantime:

## Summary

```mermaid
sequenceDiagram
    participant Client
    participant TMS
    participant DPS
    participant CRSP
    participant Rules
    participant TProc
    participant CADProc
    participant TADProc
    participant ResDB
    participant CMS

    Client->TMS: Evaluate data
    TMS->DPS: 1-to-1 via NATS
    DPS->CRSP: 1-to-1 via NATS
    DPS->TMS: 200 OK
    TMS->Client: 200 OK (evtId)
    CRSP->Rules: 1-to-many pub, 1-to-1 sub
    CRSP->DPS: 200 OK
    Rules->TProc: 1-to-1 pub, many-to-1 sub
    Rules->CRSP: 200 OK
    TProc->CADProc: 1-to-1 via NATS
    TProc->Rules: 200 OK
    CADProc->TADProc: 1-to-1 via NATS
    CADProc->TProc: 200 OK
    TADProc->ResDB: Write result
    ResDB->TADProc: 200 OK
    TADProc->CMS: 1-to-1 via NATS
    TADProc->CADProc: 200 OK
```

## Proposed pattern for all processors

ONLY on transaction:
1. If the output stream (`subject`) does not exist, create the output stream (`subject`) and send to the `subject` in the stream, throw an error
2. Publish to the output stream

On startup:
1. Create the upstream/input stream if it does not exist and subscribe to it, and throw a warning

## Configurability
1. Explore the ability to alter the implementation configuration options to change processor pub/sub behaviour without code changes, e.g. changing the stream/`subject` configuration from 1 stream, multiple subjects to multiple streams, 1 subject per stream.

## Processors

- [x] TMS
- [x] Data Preperation
- [x] CRSP
- [x] Rule-Executor
- [x] Typology Processor
- [x] TADP
- [x] CADP

**Comment by JeanPierreNell** [comment]
Allowed Multiple Subjects when consuming and publishing Messages: 
https://github.com/frmscoe/frms-coe-startup-lib/pull/5

**Comment by JeanPierreNell** [comment]
Fixed Multiple Subject Issue: 
https://github.com/frmscoe/frms-coe-startup-lib/pull/7

**Comment by JeanPierreNell** [comment]
Fixed Issue with Exporting Producer INIT as well as default producer Stream usage.
https://github.com/frmscoe/frms-coe-startup-lib/pull/8

**Comment by JeanPierreNell** [comment]
Fixed issue on Arango Lib: 
https://github.com/frmscoe/frms-coe-lib/pull/36
