### ISSUE TITLE
Set up new Elastic version in SB4 and SB3

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#138]

**Comment by vorsterk** [comment]
Completed this task yesterday , I installed the latest version of ELK stack on Sandbox3 and Fixed the APM logging on Sandbox4 
![image](https://github.com/frmscoe/General-Issues/assets/93905748/3bd28ecc-6a9a-4519-b6e3-fb4fbe8feb1d)
![image](https://github.com/frmscoe/General-Issues/assets/93905748/c1a8349e-b0b7-4390-aa5d-55e0da6cc8b5)
