### ISSUE TITLE
Address Critical Container Vulnerability Findings

### ISSUE THREAD

**Issue by johanfol** [frmscoe/General-Issues#145]
Container registry images should have vulnerability findings resolved (powered by Microsoft Defender Vulnerability Management)

![image](https://github.com/frmscoe/General-Issues/assets/36838637/1e53748c-b188-45d6-959b-309f1fd93f84)

Three major issues affecting all our containers:
![image](https://github.com/frmscoe/General-Issues/assets/36838637/60d77dcc-e6d8-4c96-a383-0ebf46c9be9d)

![image](https://github.com/frmscoe/General-Issues/assets/93905748/8c777002-586f-48e7-826d-9b972e5475f1)
![image](https://github.com/frmscoe/General-Issues/assets/93905748/0a3a70a2-e919-42f4-a142-8caa36e6b5e0)

Jenkins worker also has a vulnerability

![image](https://github.com/frmscoe/General-Issues/assets/93905748/8b33d21c-d37d-48f3-8414-bfe8503b5730)

**Comment by vorsterk** [comment]
https://snyk.io/test/docker/node%3A16.17.0-alpine

Link to vulnerabilities in 16.17-alpine

**Comment by Justus-Ortlepp-frms** [comment]
Completed, archiving.
