### ISSUE TITLE
Upgrade Arango to 3.11 to leverage latest performance improvement features

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#150]

**Comment by vorsterk** [comment]
Task Completed , Upgrade done from v3.10 to v3.11 . Removed the clustered version of arango and installed the single instance. Updated SB4 document with new password , Jenkins variables changed.

![image](https://github.com/frmscoe/General-Issues/assets/93905748/43f3670c-ff58-460b-847e-cde916d2a359)
