### ISSUE TITLE
HELM improvements and upgrades

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#155]
## Story statement

**As a** [the beneficiary of this feature],
**I want** [what does the beneficiary want to be able to do?],
**So that** [what is the benefit or value of the feature?]
**And so that** [list ALL the benefits, one at a time]

## Acceptance criteria
1. [How will we know that the feature is completely and correctly implemented?]

**Comment by vorsterk** [comment]
Duplicate task https://github.com/frmscoe/General-Issues/issues/378

Closing this task.
