### ISSUE TITLE
Arango DB upgrade rule refactor

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#156]
The latest Arango DB upgrade, and the implementation of split databases, has resulted in some rules needing to be redeployed and also for some rules to be updated to point to the correct collection in the transactionHistory database.

Rules to be redeployed:

001 - redeployed, tested
003 - redeployed, tested
004 - redeployed, tested
006 - redeployed, tested
007 - redeployed, tested
008 - redeployed, tested
016 - redeployed, tested
020 - redeployed, tested
021 - redeployed, tested
025 - redeployed, tested
048 - redeployed, tested
075 - redeployed, tested

**Comment by Justus-Ortlepp-frms** [comment]
Rule 007: The second query needs to point to the `transactionHistoryPacs008` collection:
https://github.com/frmscoe/rule-007/blob/main/src/rule-007.ts#L98C20-L98C38
