### ISSUE TITLE
Out of order data processing from asynchronous TMS

### ISSUE THREAD

**Issue by Lenbkr** [frmscoe/General-Issues#184]
TMS has race conditions with Data Preparation when scaling these services. 
Solution: Ensure all transactions are synchronous so transaction sets are processed in correct order.

TMS: Replace outgoing networking (remove NATS add Axios)
DataPrep: Replacing incoming networking (add KOA, keep NATS outgoing)

![Nats race condition](https://github.com/frmscoe/General-Issues/assets/36838637/d60140d6-e0af-44da-9df0-8791c69be06c)

**Comment by Lenbkr** [comment]
Related: https://github.com/frmscoe/General-Issues/issues/190

**Comment by Justus-Ortlepp-frms** [comment]
Completed, archiving.
