### ISSUE TITLE
Redis Optional In library

### ISSUE THREAD

**Issue by JeanPierreNell** [frmscoe/General-Issues#19]
Redis is currently required when using the Global Library - this includes when we try and use it as a Class Library. As a effect, we now have to maintain a additional connection to Redis.

We require redis to only be required if another Database connection, like the transaction history is established.

As an Developer,
I want to be able to use the library as a class library,
So that I can easily access our global classes, without a Arango or Redis connection.

**Comment by Lenbkr** [comment]
Issue fixed in https://github.com/frmscoe/frms-coe-lib/pull/7
