### ISSUE TITLE
Replace the NATS pub/sub between TMS API and DataPreparation with a REST interface

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#190]
**As an** Actio client platform operator,
**I want** to know when a message has been sufficiently processed by the Actio platform,
**So that** I can send the next message in a chain of interdependent messages

## Acceptance Criteria
1. Replace the NATS pub/sub between TMS API and Data Preparation with a REST interface
2. When Data Preparation has completed the processing of a message it had received, it must respond to the TMS API with a 200 OK
3. When the TMS API receives a 200 OK from the Data Preparation Service, it must respond to the client platform with a 200 OK

**Comment by Lenbkr** [comment]
Reverting change

**Comment by Justus-Ortlepp-frms** [comment]
Completed, archiving.
