### ISSUE TITLE
Collapse TMS and DP into a single service

### ISSUE THREAD

**Issue by johanfol** [frmscoe/General-Issues#199]
`@startuml

actor Actor1 as "Actor"
participant tms as "Transaction Preparation Service"
participant nats as "Nats"
participant crsp as "CRSP"

autonumber

group Collapse TMS/DP Implementation
        Actor1 -> tms: POST Pain.001 via HTTP
        tms -> tms: Save Data Cache
        tms -> nats: Publish via Nats
        nats -> crsp: Publish via Nats
        tms -> Actor1: Return Message

        Actor1 -> tms: POST Pacs.002 via HTTP
        tms -> tms: Get Transaction Cache
        tms -> nats: Publish Pacs.002 with Cache
        nats -> crsp: Process Pacs.002
        tms -> Actor1: Return Message
end

@enduml
`

![Image](https://github.com/frmscoe/General-Issues/assets/36838637/2db7059e-6bc1-4acf-a489-7d0af59477dc)

**Comment by Justus-Ortlepp-frms** [comment]
https://github.com/frmscoe/General-Issues/issues/200
