### ISSUE TITLE
Scale up Sandbox 2

### ISSUE THREAD

**Issue by johanfol** [frmscoe/General-Issues#20]
We're having trouble submitting 50K transactions to the sandbox environment, and the queries to arango is causing timeouts. Let's try the following to be able to achieve the benchmark. 

- Add a new VM (so that there should be 5 in total)
- Add ArangoDB (standalone instance, not clustered as there is now) to the new VM so it can hopefully keep up with 50K transactions we're planning to submit to the environment.

**Comment by vorsterk** [comment]
A new node was added to Sandbox 2 for the task JP is working on to import the data for Bankserv , I will assist JP if he has any other issues.
