### ISSUE TITLE
Implement and evaluate ClinicFlame.js

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#219]
Establish a CPU profile on local for all processors.

Objective: visualise profile and identify bottlenecks

Success: Create list of improvements for different stories
Failure: Escalate for team discussion
- [x] TMS
- [x] CRSP
- [x] TP
- [x] CADP
- [x] TADP

**Comment by Lenbkr** [comment]
Updated Checklist

**Comment by Lenbkr** [comment]
New Issues 
https://github.com/frmscoe/General-Issues/issues/238
https://github.com/frmscoe/General-Issues/issues/240
https://github.com/frmscoe/General-Issues/issues/241
https://github.com/frmscoe/General-Issues/issues/242
https://github.com/frmscoe/General-Issues/issues/243
https://github.com/frmscoe/General-Issues/issues/244
https://github.com/frmscoe/frms-coe-startup-lib/issues/18

**Comment by Justus-Ortlepp-frms** [comment]
Completed, archiving.
