### ISSUE TITLE
Update the Alert Summary report extracted from the transaction evaluation results

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#233]
Current report:
![image](https://github.com/frmscoe/General-Issues/assets/123470803/aa539e0d-4202-4473-b114-2703c6673aba)

## Changes required:

1. Summary information to render as follows:
    a. Total number of transactions processed
    b. Total value of transactions processed
    c. Total number of transactions containing known fraud
    d. Total value of transactions containing known fraud

2. Table contents (line items)
    a. **Total number alerted**: Total number of transactions where any typology breached its threshold (greater or equal)
    b. **Total value alerted**: Total amount of transactions where any typology breached its threshold (greater or equal)
    c. **Total number detected**: Total number of transactions containing known fraud where any typology breached its threshold (greater or equal)
    d. **Total value detected**: Total value of transactions containing known fraud where any typology breached its threshold (greater or equal)
    e. **Total number missed**: 1(c) - 2(c)
    f. **Total value missed**: 1(d) - 2(d)
    g. **% Volume detected**: 2(c) / 1(c)
    h. **% Value detected**: 2(d) / 1(d)
    i. **Total number false positive**: 2(a) - 2(c)
    j. **% false positive**: 2(i) / 2(a)

![image](https://github.com/frmscoe/General-Issues/assets/123470803/0d323689-6d4d-482b-b4c9-a68e61d966e2)

3. The data above must be separated into columns for specific months in the dataset (by timestamp) (month 1 to month 13)

4. Render reports in landscape orientation by default

**Comment by johanfol** [comment]
Initial feedback:

- [ ] change heading at the top of the report from "Reported" to "Alerted"
- [ ] change "count" to "volume"
- [ ] transpose the table (I think you made the right decision) - leave as is for now.
- [ ] remove "Not alert count" and percentage
- [ ] missing the totals from the bottom of the column
- [ ] include false-positive ratios
- [ ] remove the pie-chart from the summary
- [ ] remove column for Fraud - Alerted amount
- [ ] add a column for the count (volume) of known fraud that was alerted

**Comment by Justus-Ortlepp-frms** [comment]
Additional requirements:

Add a ratio column for the ratio of false positives to detected: The false-positive ratio is the 1 : total volume detected (Fraud volume in the table) / total Alert Volume. e.g. for 1-2022 this is expressed as 1 : (2418 / 328) = 7.37 (round to two decimal places).
Rename reference to "number" to "volume"

**Comment by Justus-Ortlepp-frms** [comment]
Completed, archiving.
