### ISSUE TITLE
Performance Hypothesis: Move the transactionHistory.transactions collection to its own instance of ArangoDB

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#239]
Ref #71 

## Acceptance criteria:
1. Implement a new instance of Arango DB running in its own container/VM.
2. Create a `evaluationResults` database on this instance
3. Recreate the `transactions` collection from the current transactionHistory database in this new database.
4. Update TADProc to submit the completed evaluation result to the `evaluationResults.transactions` database.

**Comment by Justus-Ortlepp-frms** [comment]
QA:


![Image](https://github.com/frmscoe/General-Issues/assets/123470803/56dc07f0-fcfc-43dd-8bc2-cd1c393967f7)



![Image](https://github.com/frmscoe/General-Issues/assets/123470803/61beddae-efd3-4c01-bbce-49a39b4013eb)
