### ISSUE TITLE
Nodejs Workers bugged

### ISSUE THREAD

**Issue by Lenbkr** [frmscoe/General-Issues#248]
Variable `numCPUs` to specify how many workers to create is bugged on the following processors

- [x] CRSP
- [x] Typology Processor

**Comment by johanfol** [comment]
When working on this, please make sure the default value for numCPUs across all processors is NOT Number.MAX_SAFE_INTEGER (since node doesn't like to spin up 9007199254740991 processors), but instead a normal value like 1 (so that worker threads are by default switched off).

**Comment by Justus-Ortlepp-frms** [comment]
Completed, archiving.
