### ISSUE TITLE
Some processors still utilise JSON when interacting with Redis

### ISSUE THREAD

**Issue by rtkay123** [frmscoe/General-Issues#276]
## Typology Processor and TADP still use json serialisation to store data in redis. We could directly serialise the JS objects to binary and store them in Redis

**As an ACTIO platform user
**I want faster serialisation,
**So that a transaction can move faster in the platform
**And so that we use less storage in Redis

## Acceptance criteria
1. No JSON stored in Redis
2. TP no longer serializes rule results as json before it caches
3. TP no longer deserializes rule results as json when it calls getMembers
2. TADP no longer serializes rule results as json before it caches
3. TADP no longer deserializes rule results as json when it calls getMembers

**Comment by johanfol** [comment]
Fix for TP here:
https://github.com/frmscoe/frms-coe-lib/pull/71
