### ISSUE TITLE
Standardized DB Manager and NATS worker instances

### ISSUE THREAD

**Issue by Lenbkr** [frmscoe/General-Issues#277]
## Story statement

**As a developer,
**I want to standardize DatabaseManager and NATS instance behaviour,
**So that only the set amount of instances are instantiated and we have consistent expectations across the product stack

## Acceptance criteria
1. A Single database manager is instantiated no matter how many workers are spun up
2. A instance of NATS for every worker is spun up.

**Comment by Lenbkr** [comment]
Testing E2E before merge.

**Comment by Justus-Ortlepp-frms** [comment]
Completed, archiving.
