### ISSUE TITLE
To Terraform or not to Terraform

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#280]
## Story statement

**As an** Actio implementer,
**I want** a convenient way to provision infrastructure for my deployment,
**So that** implementations can be easily and predictably automated.

## Acceptance criteria
1. Evaluate Terraform's current licensing scheme against Actio and its adopters' requirements
2. Identify alternatives to Terraform that also meets the IAC requirements of the Actio platform
3. Report for a Design Authority decision

**Comment by johanfol** [comment]
At Mojaloop it was discussed and the outcome is that since Terraform would not be the core offering, but instead, a supporting service part of the ML pipeline, there should not be at risk of violation of the license. The same could be said for us - hence I'd move to use Terraform for our IAC.

**Comment by Justus-Ortlepp-frms** [comment]
Completed, archiving.
