### ISSUE TITLE
Latest tag on Jenkins deployment don't consistently deploy the latest rule

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#288]
## Issue

Jenkins deployment with `@latest` uses the cached version of a processor and not the actual latest version. Attempt to recreate and investigate fix.

**Comment by JeanPierreNell** [comment]
Resolved issue by adding : --no-cache in the Jenkins Docker-Build Command, as it currently caches the Docker Image.

For example, on Rule 002 , before:

```docker build -t `LOCATION:1.0.0 .```

after: 

```docker build -t LOCATION:1.0.0 --no-cache .```
