### ISSUE TITLE
Investigate bun memory usage

### ISSUE THREAD

**Issue by johanfol** [frmscoe/General-Issues#289]
## Story statement

**As a** eKuta infrastructure consultant,
**I want** to understand what the expected memory footprint for a bun application would be ,
**So that** I can effectively estimate how much RAM I would require on infrastructure 
**And so that** I can know what my production environment would cost

## Acceptance criteria
I know what a rule processor memory footprint is when it's idling, and I have a separately documented footprint of how memory usage goes up (and down) when it is hit with low volumes of transactions. 

For example, currently footprint for a NodeJS rule processor is this, and the little peaks are when a transaction comes through:

![Image](https://github.com/frmscoe/General-Issues/assets/36838637/d791a938-6127-4933-ae94-303e53eeb766)

And then for Bun, this is the current usage:

![Image](https://github.com/frmscoe/General-Issues/assets/36838637/fa38757f-90ac-4c45-a8e2-290c59b07648)

This ticket asks to find out if this is  the best usage a bun app can get, and that it is normal to idle at ~210MB RAM, and when a single transaction comes through, peak up to ~410MB of RAM? Or is there a way to deploy a bun app to have a smaller memory footprint, and significantly smaller peak when a transaction comes through.

**Comment by Justus-Ortlepp-frms** [comment]
Blocked: When we visited it, lots of issues were being opened in the Bun repo with cases similar to ours, as of then, the issues were still open. But hopefully, due to time passing, some bugfixes may have been implemented upstream.

**Comment by Justus-at-Tazama** [comment]
We abandoned Bun for now
