### ISSUE TITLE
Evaluate NATS as a suitable pub/sub/queuing solution for Actio

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#3]
**As an** Actio Platform Operator,
**I want** the rule processors to publish their results on a queue
**and I want** the typology-specific processors to subscribe to their specific rules' results
**So that** rule result collisions can be better managed
**and so that** performance issues can be more transparent
**and so that** process failure recovery can be facilitated

```mermaid
sequenceDiagram
    participant rules as Rule Processor
    participant pub as Redis Queue
    participant typp as Typology Processor
    participant cadp as CAD Processor
    participant cache as Processor Cache
    participant cfg as Config Store
    participant cms as Case Management

loop for each rule
    rules ->> pub: Publish rule result
    pub ->> typp: Submit rule result
    activate typp
    loop for each subscribing typology
        activate typp
        typp ->> typp: Determine all rules
        typp ->> cache: Fetch cached rule results
        typp ->> typp: Check typology completion
        alt outstanding rule results
            typp ->> cache: Cache rule result
        else all rule results received
            alt typology config in cache
                typp ->> cache: Fetch typology configuration
            else typology config not in cache
                typp ->> cfg: Fetch typology configuration
            end
            deactivate typp
            typp ->> typp: Calculate typology score
            typp ->> cms: Send alert
            typp ->> cadp: Aggregate typology results
        end
        typp ->> rules: Response
        deactivate typp
    end
end
```

## Acceptance Criteria

![image](https://github.com/frmscoe/General-Issues/assets/123470803/71a57ab2-b51c-420e-82a8-641bf1da02a6)

1. Evaluate NATS in the above context.

    a. Create a CRSP-analog processor to publish a transaction for the consumption of 5 rule-analog processors

    b. Create 5 rule-analog processors to consume the output of the CRSP-analog

    c. Create a random delay inside the rule-analog processors of up to 100ms

    d. Publish the outcome of the rule-analog processors to their own channel

    e. Create 5 typology-analog processors to consume the output of the rule-analog processors

    f. For each typology-analogs, subscribe to a different sub-set of rule-analogs. Once all subscriptions have been received, collate the rule-analog inputs and publish a typology-analog result to each typology-analog processor's own channel

    g. Create a TADProc-analog processor to consume data from the 5 typology-analog processors. Subscribe the CADProc-analog to all typology-analogs. Once all subscriptions have been received, collate the typology-analog inputs and log a transaction-analog result.

### Rule to Typology flow (suggestion):
R1 to T1, T2
R2 to T2, T3, T4
R3 to T1, T2, T3, T4, T5
R4 to T3, T4, T5
R5 to T4, T5

2. Evaluate:

    a. Dynamic scaling: Can the number of processors in a "function group" be scaled dynamically?

    b. Performance: How many transactions per second can the end-to-end chain handling without collapsing? What is the practical maximum?

    c. Ease of use: how intuitive and easy is the setting up of the environment?

    d. Performance monitoring: What tools are available to report/alert on channel congestion?

3. Produce a report with the findings.

**Comment by johanfol** [comment]
Done - demo results showed it's suitable, we're moving ahead to write a library for the above.
