### ISSUE TITLE
Update SB3 to the latest release (1.2.0)

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#321]
Update SB3 to the latest release (v1.2.0).

Environment-specific settings:

- pain.001/013 disabled
- transaction results in the TransactionHistory.transactions collection
- Logging on and verbose (high? Debug?)

**Comment by Justus-Ortlepp-frms** [comment]
Please update the related Sybrin components.

**Comment by Lenbkr** [comment]
Latest version deployed.
E2E Reports restored.

Outstanding: Config Manager
