### ISSUE TITLE
BUG: Full-Stack-Docker-Actio is not updated with recent main branch changes

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#365]
Deployment of TMS API and Rule Processors as part of the Docker Stack is malfunctioning due to the changes to split the ArangoDB collections.

**Comment by rtkay123** [comment]
Caused by:
https://github.com/frmscoe/rule-executer/pull/82
https://github.com/frmscoe/tms-service/pull/102
