### ISSUE TITLE
Update the Full-Stack_Docker_Actio codebase to level with main

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#367]
The configuration of the Full-Stack-Docker-Actio repo is out of step with the current configuration of processors for a main-branch deployment.

Also update the definition of done to ensure that any future changes that may impact the Docker Compose deployment of the platform are also made in the Full-Stack-Docker-Actio repo.

**Comment by rtkay123** [comment]
https://github.com/frmscoe/Full-Stack-Docker-Actio/pull/3
