### ISSUE TITLE
BUG: Rule "reason" attribute is missing for ".err" outcomes

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#368]
Original requirement: https://github.com/frmscoe/General-Issues/issues/281

Also see clarification: https://github.com/frmscoe/General-Issues/issues/281#issuecomment-1757054985

The `reason` attribute in the ruleResult object should be defined as optional so that it can contain the description of any .err outcomes
The `reason` attribute will be omitted entirely if the rule result is not an error condition

At the moment the rule `reason` is missing for `".err"` outcomes.

**Comment by rtkay123** [comment]
I think the application was in some form of unhealthy state and it reached code that should have been unreachable if setup properly. In any case, being explicit, added an explicit check with https://github.com/frmscoe/rule-executer/pull/98 that should address this.
