### ISSUE TITLE
Deployment Documentation Update

### ISSUE THREAD

**Issue by rtkay123** [frmscoe/General-Issues#377]
# Setting Up
In setting up the ingress controller for nginx, I had some issues locating the chart specified in the helm repo:

The docs mention:
`helm install nginx-ingress-controller Tazama/nginx-ingress-controller --namespace=ingress-nginx`

However, the chart `nginx-ingress-controller` does not exist in the `Tazama` repo. The actual name is `ingress-nginx`, so in actuality, I had to run:
`helm install nginx-ingress-controller Tazama/ingress-nginx --namespace=ingress-nginx`

## Path specifics

I could not copy my Jenkins pipelines, because the paths or directories are specific to separate Jenkins charts. I had setup Jenkins with the AKS guide, however in the EKS guide, the destination to which files were copied was different. I think the ask is to note that paths *can* be different for Jenkins installations, it seems obvious in retrospect because you'll get a 'directory does not exist' error, but for some users, it can be confusing why they can't copy a file somewhere.

```sh
kubectl cp . <name of pod>:/var/jenkins_home/jobs/ -n cicd
```
The directory `/var/jenkins_home/jobs/` May not exist in your Jenkins version or installation, so it may be good to note that users should verify the destination exists if they are getting errors there as they may need to copy to a different destination.

## Setting up Ingresses
Docs mentioned setting up an ingress with the command:
```sh
helm install kibana Tazama/kibana --namespace=development --set ingress.enabled=true
```
This was after I had run:
```
helm install kibana Tazama/kibana --namespace=development
```

If possible, it would be more concise to skip the reinstall on the second either by enabling ingress when we install Kibana initially, or perhaps, if possible, setting the ingress on the already installed Kibana

# Jenkins Issues
I think users should be notified that some versions of plugins may not be available or deprecated at a particular point in time. My Jenkins failed to install with the preconfigured plugins as a cause of that. 

## Environment Variables
I think it's worth to note where each environment variable is used, perhaps have two sections for variables, **Jenkins Scoped Variables** and perhaps, **Processor Scoped Variables**.

Some variables have the same type of value but there are different restrictions to them - example: some passwords which should be surrounded by single quotes, but in other areas, those exact values don't require single quotes. The reason is because some variables are passed down to the processors, and they need those single quotes to pass the values exactly as they are, including special characters, (e.g. `$`), which can break how NodeJS reads environment files. But some passwords **can** be generated which include no special characters so we don't need the single quotes. 
> Suggestion: For variables used by the processors, it's a good rule of thumb to encapsulate them by single quotes so special characters are read as part of the value. Those used by Jenkins don't need this requirement

I think we should provide some context to why somethings are done a certain way, and to that extent, consequences of those decisions. In this case, "if there are no single quotes on these variables which are sent to the processors, your environment may break if it contains special characters as they are not escaped"

## Pipeline Specifics
I think we should also note that users *should* verify that on each job they have imported, the required values are populated. For example, values from combo boxes or dropdown menus. Usually for credentials, they aren't automatically selected. It's worth noting that even after populating your environment variables and setting your configuration using the exact names in the guide, it may not translate to them being applied automatically and you have to check each job (or each failing job) to see if the configuration is setup properly.

## Misc
Sometimes, Jenkins requires restarts and sometimes it resets some preferences, it may be due to a specific jenkins version or a bug, however, I recall enabling "Disable Https Certificate Check" and after sometime, finding it disabled again, it may be worth to note that in troubleshooting.

## Elastic Search and Memory

I had issues deploying some processors because I was running out of memory. The cause, elastic search was idling at about 17.5Gb of RAM. I think we should perhaps have a section of suggested values for config and limiting. Perhaps a percentage that whomever is deploying can reason with in respect to their hardware. For example: "Set a max memory limit for elastic search to be at around 5-10% of the total available memory, so on 128Gb of RAM, you can set elastic to have 6Gb limit), and as mentioned before with consequences, let the reader know what *may* happen if they choose to ignore this step.

**Comment by vorsterk** [comment]
**Path specifics:**

ingress-nginx name for helm installation change it was a typo.

**Setting up Ingresses:**

It is in the documentation but I moved it above the helm installation part so its added if needed.

**Environment Variables:**

I do specify why there are additional values for arango in the document.
![image](https://github.com/frmscoe/General-Issues/assets/93905748/8c6125c5-043a-46f4-ac2f-eeffd8402d31)

Single quotes:

Its was specified in the documentation.
![image](https://github.com/frmscoe/General-Issues/assets/93905748/15ab4c34-211c-44c6-acae-66de084d45c7)


**Jenkins requires restarts and sometimes it resets some preferences**

Will add this.

**Elastic Search and Memory**

Elastic was consuming lots of memory but the issue was that the jenkins builder agent was running out of memory when runing to build because the limit was set to 500mbs. I will add this into the documentation .

**Comment by rtkay123** [comment]
> I do specify why there are additional values for Arango in the document.

Yes, you do. I think I maybe explained poorly. I meant in the case of:
![image](https://github.com/frmscoe/General-Issues/assets/70331483/9250629e-76ef-4df0-a238-5fff931b4079)

And this:
![image](https://github.com/frmscoe/General-Issues/assets/70331483/30635469-d8dc-45e0-8836-7d8d085d2d57)

Keeping your analogy, that's the same key for the same room (if you're using the same DB instance). But the keys look different. Namely, one requires quotes and the other doesn't. I just meant it would be worth to note why that is. Basically, why MUST I use single quotes on one, and the other has no such restriction if I am unlocking the same room with the same key? If that was covered somewhere, I think I missed it

Otherwise, I think everything else is solid

**Comment by vorsterk** [comment]
Ingress issues for AKS - Will need to added inbound outbound rules on the cluster , will add additional info once Devops has checked

**Comment by vorsterk** [comment]
Task closed and completed.
