### ISSUE TITLE
Default deployment indexes are incorrect in ArangoDB

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#379]
e.g. the pacs.008 collection in transactionHistory database contains an index for EndToEndId at the root of the incoming message, but this causes a second incoming message to fail on an index conflict.

![Image](https://github.com/frmscoe/General-Issues/assets/123470803/cba41678-7dc6-4d88-b3ed-0da00be35ce1)

## Acceptance criteria

1. Recommend a review of all indexes set up during a deployment and alignment with the indexes identified out of performance benchmarking.

**Comment by johanfol** [comment]
Update: Indexes from 5-Fetch-Indexes, created in "Create All Indexes" script, is being moved to 2-Create-Indexes folder instead, as individual indexes. Rodney will also create necessary document therefore.

**Comment by rtkay123** [comment]
Fixed with: https://github.com/frmscoe/postman/pull/42

Relevant docs: https://github.com/frmscoe/docs/blob/main/Technical/Database/arango-db-deployment-indexes.md
