### ISSUE TITLE
Add maxcpu variable to the Rule Executor

### ISSUE THREAD

**Issue by vorsterk** [frmscoe/General-Issues#383]
## Story statement

**As a** Tazama Operator,
**I want** to control the maximum CPU usage for containers via an environment variable,
**So that** the system can dynamically allocate CPU resources without exceeding a predefined limit, ensuring efficient resource management and preventing any single container from monopolizing CPU resources.

**Method -** This parameter will be used for performance enhancements. 

## Acceptance criteria
1. Validation of MAX_CPU variable existence: The MAX_CPU environment variable should be present in all Dockerfiles where CPU usage needs to be controlled.
2. Correct usage of MAX_CPU: The MAX_CPU variable should be correctly used in the Dockerfile to set the CPU limit. 

- If you set the maxcpu=3 , then 3 workers need to be spun up.

3. Documentation: All changes should be documented, clearly explaining how to set and modify the MAX_CPU variable.
4. Testing: Automated tests should confirm that the CPU limits are enforced according to the MAX_CPU setting.
5. Resource Optimization: After the introduction of MAX_CPU, there should be an observed improvement in resource allocation across the system.

Variable : ENV MAX_CPU=

**Comment by JeanPierreNell** [comment]
Code is live on: https://github.com/frmscoe/rule-executer/tree/max_CPU
