### ISSUE TITLE
`Amt` Serialisation fails in transit

### ISSUE THREAD

**Issue by rtkay123** [frmscoe/General-Issues#390]
`TADP` `report.transaction` has missing amount fields. The platform uses `Amt` in the `dataCache` but the one sent to `report.transaction` is not serialised properly.

A fix is on this branch, not yet merged:
https://github.com/frmscoe/frms-coe-lib/tree/fix/amt

## Acceptance criteria
1. Amt fields are correctly serialised and reflect in `report.transaction`

**Comment by Justus-at-Tazama** [comment]
![image](https://github.com/frmscoe/General-Issues/assets/123470803/1201e43b-a7fe-4f44-a23d-5b615e6aa0b1)

Regression/e2e testing result
