### ISSUE TITLE
Performance testing - Indexes on all rule queries

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#67]
## Performance Hypothesis

All queries to Arango include filters and these filters need to target indexed attributes to improve query performance.

## Testing approach:

1. Ensure that all rule queries use appropriate indexed data - update database / collection definitions where appropriate.

    a. Indexing must preserve existing document JSON structure - i.e. do not "surface" indexed fields, but index "in situ"

4. Re-run previous performance test ingestion pack.
5. Compare average and peak throughputs (TPS) and average turnaround time per transaction (API ingestion to evaluation result posting in milliseconds) results to previous benchmark - #65

**Comment by cshezi** [comment]
Blocked due to Testing Data not yet being available (TPS)
