### ISSUE TITLE
Performance testing - caching of duplicated queries

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#68]
## Performance Hypothesis

Database interaction (disk) is slower than cache interaction (memory). If disk-based database reads can be avoided through cache-based reads for the same queries, platform performance will improve.

## Testing approach:

1. Identify and abstract identical queries that run across multiple rules so that the query results are only returned once (the first time a query is run) and cached so that other queries can retrieve the results from cache instead of via a full database read.
2. Re-run previous performance test ingestion pack.
3. Compare average and peak throughputs (TPS) and average turnaround time per transaction (API ingestion to evaluation result posting in milliseconds) results to previous benchmark - #67

**Comment by Justus-Ortlepp-frms** [comment]
A detailed analysis of the rules showed very little re-usable or non-unique queries and caching is unlikely to be an effective means of improving performance at this time.

**Comment by JeanPierreNell** [comment]
Issue is closed per discussion. Deemed unlikely to increase performance at all, at the cost of pitfalls.
