### ISSUE TITLE
Performance testing - Arango research to improve memory utilization and caching

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#72]
Arango utilization is currently unexpectedly low. This creates an opportunity to create a larger caching reliance to improve database performance. This task is to research a more efficient and effective use of Arango memory utilization for possible performance gains.

Acceptance criteria

1. Produce a report and backlog

**Comment by Lenbkr** [comment]
Improve Memory Utilization
