### ISSUE TITLE
Refactor rules to abstract rule queries

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#74]
Arango queries from the rules have been consolidated and abstracted into the code library. This task is to refactor the rules to now implement queries from the library.

## Acceptance criteria
- [ ] 001	Rule: Derived account age - creditor
- [ ] 002	Rule: Transaction convergence - debtor
- [ ] 003	Rule: Account dormancy - creditor
- [ ] 004	Rule: Account dormancy - Debtor
- [ ] 006	Rule: Outgoing transfer similarity - amounts
- [ ] 007	Rule: Outgoing transfer similarity - descriptions
- [ ] 008	Rule: Outgoing transfer similarity - Creditor
- [ ] 010	Rule: Increased account activity: volume - debtor
- [ ] 011	Rule: Increased account activity - Creditor
- [ ] 016	Rule: Transaction convergence - creditor
- [ ] 017	Rule: Transaction divergence - Debtor
- [ ] 018	Rule: Exceptionally large outgoing transfer
- [ ] 020	Rule: Large transaction amount vs history - Creditor
- [ ] 021	Rule: A large number of similar transaction amounts - Creditor
- [ ] 025	Rule: Aggregated transaction mirroring
- [ ] 027	Rule: Immediate transaction mirroring
- [ ] 028	Rule: Debtor age
- [ ] 030	Rule: New Creditor transfer
- [ ] 034	Rule: Watch-listed account - Debtor
- [ ] 035	Rule: Watch-listed account - Creditor
- [ ] 036	Rule: Watch-listed party - debtor
- [ ] 037	Rule: Watch-listed party - creditor
- [ ] 044	Rule: If the debtor has never performed a successful transaction before
- [ ] 045	Rule: If the creditor has never received a successful transaction before
- [ ] 048	Rule: Large transaction amount vs history - Debtor
- [ ] 054	Rule: Synthetic data check - Benford's Law - Debtor
- [ ] 063	Rule: Synthetic data check - Benford's Law - Creditor
- [ ] 074	Rule: Distance over time from last transaction location
- [ ] 075	Rule: Distance from habitual locations
- [ ] 076	Rule: Time since last transaction - Debtor
- [ ] 078	Rule: Cash withdrawal
- [ ] 083	Rule: Multiple accounts associated with a debtor
- [ ] 084	Rule: Multiple accounts associated with a creditor
- [ ] 090	Rule: Upstream transaction divergence
- [ ] 091	Rule: Transaction amount vs regulatory threshold

**Comment by johanfol** [comment]
Deployed v0.0.6
Changes
Pseudonyms:
   Added
   getPacs008Edge(endToEndIds: string[])
    getPacs008Edges(creditorId: string, threshold: string, amount: number)
   getPacs002Edge(endToEndIds: string[])
   getDebtorPacs002Edges(debtorId: string)
   getSuccessfulPacs002Edges(creditorId: string, debtorId: string, endToEndId: string)
    getDebtorPacs008Edges(debtorId: string, endToEndId: string)
   getCreditorPacs008Edges(creditorId: string)
   getPreviousPacs008Edges(debtorId: string, limit?: number, to?: string[])
   getCreditorPacs002Edges(creditorId: string, threshold: number)

   Updated
   getPseudonymGeneric to queryPseudonymDB(collection: string, filter: string, limit?: number)

TransactionHistory:
   Added
   getSuccessfulPacs002Msgs(endToEndId: string)
   getSuccessfulPacs002EndToEndIds(endToEndIds: string[])
   getDebtorPacs002Msgs(endToEndId: string)
    getEquivalentPain001Msg(endToEndIds: string[])
   getAccountEndToEndIds(accountId: string, accountType: AccountType)
   getAccountHistoryPacs008Msgs(accountId: string, accountType: AccountType)

   Updated
   getTransactionGeneric to queryTransactionDB(collection: string, filter: string, limit?: number)
    getDebitorPain001Msgs to getDebtorPain001Msgs(debtorId: string)

Configuration:
   Updated
   getConfigurationGeneric to queryConfigurationDB(collection: string, filter: string, limit?: number)

**Comment by Justus-Ortlepp-frms** [comment]
Completed, archiving.
