### ISSUE TITLE
Performance testing - embedding graph object identifiers in the payload

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#76]
## Performance Hypothesis

Database interaction (disk) is slower than data interaction via memory. If disk-based database reads can be avoided by embedding known information into the event payload, platform performance will improve.

## Testing approach:

1. Update the Data Preparation Service to append database object identifiers to the payload when the graph data is written during the graph transformation step.

## Payload sample:

``` json
{
    "TxTp": "pain.001.001.11",
    "CstmrCdtTrfInitn": {},
    "DataCache": {
        "dbtrId": "4bc5-beed-43da-95a6-ca7069c10019",
        "cdtrId": "a3fd-4305-4643-82dd-4f637efb0526",
        "dbtrAcctId": "97aba7ace7a1c93ede16d687a512c774eb2da5b73254a363b0fa60e5f6078a15",
        "cdtrAcctId": "6227cd4eb56186b11258f9461dbdd591bc138428e7e1f995d3addd26f61c05da"
    }
}
```

Note: Not all messages will have access to all the information. pain.001, pain.013 and pacs.008 would likely have the full set; pacs.002 would not have the dbtrId or the cdtrId (I think).

2. Add an interface to the code library so that downstream rule processors can interpret the updated event payload object. Refactoring of the downstream processors will be performed from the code library.

    a. A note for downstream processors. If a downstream processor tried to retrieve data that is not present in the `dataCache` object, the downstream processor must fetch the data from the database instead.

3. The _key value from the database must be added to the `DataCache` object - in other words, the collection prefixes (`entities` and `accounts`) must not be part of the data.
4. When the pain.001 for a specific message is processed and the `DataCache` compiled, all the identifiers must be cached in Redis. When the later messages (pain.013, pacs.008 and pacs.002) are processed, the data preparation service must first check Redis cache and build its `DataCache` object from cache. Any missing information must then be read from the database. I recommend using a graph traversal to retrieve the `dbtrId` and `cdtrId` via the `account_holder` edge collection.

## Testing guidelines

1. Generally, the message that is passed onto the CRSP from the Data Preparation Service is also returned to the TMS API and we should be able to intercept this message and inspect it to ensure that the required data elements have been added.
2. The updated payload must be tested for the pain.001, pain.013, pacs.008 and pacs.002 messages.

**Comment by JeanPierreNell** [comment]
Concluded with pull request : https://github.com/frmscoe/data-preparation/pull/12
